# Generated by Django 5.0.2 on 2025-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
